name: noboatlag
description: Fix "BoatLag", sometimes known as quantum entanglement
author: microwavedram
version: '1.5-SNAPSHOT'
main: uk.cloudmc.microwavedram.noboatlag.NoBoatLag
api-version: '26.2'
folia-supported: true

commands:
  noboatlag:
    description: "Reload Configuration"
    permission: noboatlag.reload
